version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes: 
      - /home/node/app/node_modules #indicates docker need not to map /app/node_modules to any local location
      - .:/home/node/app #indicates docker to tamp current working directoru(.) to /app directory of container
  tests:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes: 
      - /home/node/app/node_modules #indicates docker need not to map /app/node_modules to any local location
      - /home/renu/frontend:/home/node/app
    command: ["npm","run","test"]